### PR TITLE
Create amplify.yml

### PR DESCRIPTION
**Pull request by ujyaworks**

### CODE REVIEW

**Comment by ujyaworks** [comment]
LGTM

**Comment by ujyaworks** [comment]
LGTM

**Comment by ujyaworks** [comment]
ok

**Comment by mrtzdev** [comment]
ok the amplify.yml file is for AWS Amplify Hosting, but i think it is  not required ?
https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html

It automatically detects the front end framework and associated build settings by inspecting the package.json file. We can otherwise add a note in the readme about this.

**Pull request closed without merging**
